metrico/qryn-view

- webpack.config.js
- webpack.config.prod.js
- fixed publicPath inside webpack, set to 'auto'
> fix publicPath

- src/actions/loadLogs.js
- src/components/LabelBrowser/QueryBar.js
- src/components/StatusBar/StatusBar.js
- src/plugins/daterangepicker/components/Nav.js
- src/plugins/daterangepicker/index.js
- src/store/createInitialState.js
- Fixed range with label (I.e. "Last 5 minutes") not updating on every search
- Fixed text-input to be editable properly
- Added a check for text-input to not break the app if "to" is earlier than "from"
> Daterangepicker fixes

- src/components/LabelBrowser/ValuesList.js
- src/scss/modules/valuesList.scss
- Fixed issue described in #34, now if label needs more than full width of the container it gets cut off with ellipsis and full version is available in tooltip on hover.
> Fixed overflowing labels

- src/actions/errorHandler.js
- src/actions/loadLogs.js
- src/components/LogView.js
- src/scss/modules/log-view.scss
- Cleans the log view when there is a response with no logs
- Adds Empty Response message on log view to do a Logs Search
- Adjust on color contrast on Logs View
Refs: #35
> fix(LogView): #35 Cleanup logs on empty result

- src/actions/LoadLabels.js
- src/actions/loadLogs.js
- src/components/LabelBrowser/QueryBar.js
- src/components/LabelBrowser/ValuesList.js
- src/plugins/charts/index.js
- src/store/createInitialState.js
**fix: Initial timerange on copy link**
- fixed initial timerange on copy link
extras:
- fixed error on tooltip mapping for label values
- fixed long time loading icon (stopped before loading all data)
Refs: https://github.com/metrico/cloki-view/issues/43
> fix: Initial timerange on copy link

- package-lock.json
- package.json
- src/actions/loadLogs.js
- src/components/LogView.js
- src/scss/modules/log-view.scss
**fixes error on showing tags on build version**
- added shortid for each log entry for precise DOM targeting
- sort on fetching data component instead of view component
> fix tags show toggle

- src/actions/loadLogs.js
- src/plugins/charts/ChartLabelList.js
- src/plugins/charts/index.js
- added labels multi selection feature for charts
- fixed styles for buttons of chart top menu (chart types and series limiter)
> fix: Chart labels multi-select

- .babelrc
- package-lock.json
- package.json
- src/actions/LoadLabels.js
- src/actions/index.js
- src/actions/loadLabelValues.js
- src/actions/setLabelValues.js
- src/actions/setLabels.js
- src/components/LabelBrowser/ValuesList.js
- src/components/LabelBrowser/helpers/querybuilder.js
- src/components/LogView.js
- src/components/MainView.js
- src/components/UpdateStateFromQueryParams.js
- src/scss/modules/log-view.scss
> Revert "Alexey log label filters"

- src/actions/LoadLabels.js
- src/actions/loadLabelValues.js
- src/actions/loadLogs.js
- src/components/LabelBrowser/QueryBar.js
- src/components/LabelBrowser/ValuesList.js
- src/components/LabelBrowser/helpers/querybuilder.js
- src/components/LogView.js
- src/components/StatusBar/StatusBar.js
- src/components/UpdateStateFromQueryParams.js
- src/services/consts.js
- src/services/index.js
- src/services/localHistory.js
- src/services/localLabels.js
- src/services/localQuery.js
- src/services/localService.js
- src/services/localUrl.js
- cleared labels on new addition / subtraction and at query execution
- added labels selection visible on label browser on submitting query
- fixed label identification as was taking symbols from outside curly braces "(" "[" of another functions and were adding as values  on label values
> fixes: #56 Manually removing label does not update state

- src/components/LabelBrowser/helpers/querybuilder.js
fix issue when adding / removing labels from labels browser
> fix content outside curly braces

- src/actions/setLinksHistory.js
- src/components/LabelBrowser/QueryBar.js
- src/components/LabelBrowser/helpers/querybuilder.js
- src/components/LogView.js
- src/components/StatusBar/StatusBar.js
- src/components/UpdateStateFromQueryParams.js
- src/plugins/queryhistory/index.js
- src/scss/modules/status-bar.scss
- src/services/localUrl.js
- src/store/createInitialState.js
- src/store/reducer.js
- Add Shared Links and Query executions with complete params History
- Add Links History starred Items
- Add shared links input filter
- Split starred in Queries and Links
- Disabled "copy link" button when there is no query at link
- Fix: editor open when sharing link
> Links History Feature

- src/plugins/charts/ChartLabelList.js
- src/plugins/charts/index.js
Feature for Matrix charts
Adds: 
- multiple labels with value displayed at same tooltip
- total labels at same time
- sorts labels inside same tooltip by value (higher first)
- fix non selected labels by default (all visible style by default)
- points highlighting at same time of x axis
- add crosshairs at chart
- fix single points at line type chart ( before were invisible )
> Multiple labels tooltip feature

- src/plugins/charts/index.js
- showing only overlapped points
> hotfix: show only overlapped

- src/components/LabelBrowser/QueryBar.js
- src/components/LabelBrowser/components/HistoryButton/HistoryButton.js
- src/components/LabelBrowser/components/ShowLabelsButton/ShowLabelsButton.js
- src/components/LabelBrowser/components/ShowLogsButton/ShowLogsButton.js
- src/components/LabelBrowser/components/styled/index.js
- src/components/LabelBrowser/helpers/debugLog.js
- src/components/LabelBrowser/helpers/onQueryValid.js
- src/components/LabelBrowser/helpers/queryInit.js
- src/components/StatusBar/components/apiselector/ApiSelector.js
- src/components/StatusBar/components/daterangepicker/index.js
- src/components/StatusBar/styled/index.js
- src/scss/modules/date-range-picker.scss
- src/scss/modules/status-bar.scss
- src/store/createInitialState.js
- src/theme/dark.js
- theming feature init
- improve buttons and inputs styles
> theming init

- src/components/DataView/styled/index.js
- src/components/StatusBar/components/daterangepicker/components/AbsoluteSelector.js
- src/components/StatusBar/components/daterangepicker/components/Heading.js
- src/components/StatusBar/styled/index.js
- src/plugins/charts/ChartLabelList.js
- src/plugins/charts/index.js
- src/plugins/queryeditor/index.js
- src/plugins/queryhistory/components/AlertDialog/AlertDialog.js
- src/plugins/queryhistory/components/CloseButton/CloseButton.js
- src/plugins/queryhistory/components/EmptyHistoryDisplay/EmptyHistoryDisplay.js
- src/plugins/queryhistory/index.js
- src/plugins/queryhistory/styled/index.js
- src/plugins/settingsmenu/styled/index.js
- src/scss/modules/date-range-picker.scss
- src/scss/modules/status-bar.scss
- src/scss/modules/valuesList.scss
- src/theme/dark.js
Components theming at: 
- status bar
- date range picker 
- 
Fixes: 
- fix date picker button size at small size
- fix query content inside history at small size
- history feature refactoring
- standarize buttons
Small sizes chart init
> fix: components theming

- src/components/LabelBrowser/components/styled/index.js
- src/plugins/charts/ChartLabelList.js
- src/plugins/charts/index.js
- src/scss/modules/log-view.scss
- Fix options type button for chart types
- fix series show amount button
- partially fix position of elements at mobile size
> fix: chart responsive init

- src/actions/loadLabels.js
- src/actions/loadLogs.js
- src/components/DataView/DataView.js
- src/components/DataView/LogsRow.js
- src/components/DataView/consts/consts.js
- src/components/DataView/helpers/index.js
- src/components/DataView/styled/index.js
- src/components/DataView/theme/theme.js
- src/components/LabelBrowser/QueryBar.js
- src/components/LabelBrowser/ValuesList.js
- src/components/LabelBrowser/components/ShowLogsButton/ShowLogsButton.js
- src/components/LabelBrowser/components/styled/index.js
- src/components/LabelBrowser/index.js
- src/components/StatusBar/components/apiselector/ApiSelector.js
- src/helpers/error.interceptor.js
- src/plugins/notifications/index.js
- fix labels at API change
- fix logs lines styles
- add severity to level colors
> Fix: labels and logs styles

- src/actions/getData.ts
- src/components/LabelBrowser/components/Buttons/Button.model.ts
- src/components/LabelBrowser/components/Buttons/ShowLogsButton.tsx
- src/components/LabelBrowser/components/QueryBar.js
- src/components/LabelBrowser/components/styled/index.ts
- src/store/createInitialState.ts
> feat: loading state button fot each query

- src/helpers/stateFromQueryParams.js
- src/qryn-ui/notifications/index.js
- src/scss/modules/notifications.scss
- src/views/DataSources/DataSource.js
- src/views/DataSources/DataSources.js
- src/views/DataSources/components/DataSourcesFiller.tsx
- src/views/DataSources/components/Header.tsx
- src/views/DataSources/styles/Container.tsx
- src/views/DataSources/ui/Button.js
- src/views/Main.js
- added fast way of filling up all datasources with same URL / basic auth
> Feat one for all

- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetail/AccordianKeyValues.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetail/AccordianLogs.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetail/DetailState.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetail/index.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetailRow.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/VirtualizedTraceView.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/index.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/types/trace.ts
- src/components/DataViews/components/Traces/Jaeger-ui/src/uberUtilityStyles.ts
- src/components/DataViews/components/Traces/TraceView.tsx
- src/components/DataViews/components/Traces/mapTracesResponse.js
- src/components/DataViews/components/Traces/useDetailState.ts
- Add visualization for events inside traces view.
> Feature traces events

- src/components/DataViews/hooks/index.js
- src/components/DataViews/views/LogsView.js
- src/components/DataViews/views/MatrixView.js
- src/components/DataViews/views/styled.js
- src/components/LabelBrowser/components/QuerySetting.js
- src/components/QueryTypeBar/index.js
**Add: tabs for different visualizations**
> feat: Use tabs for different vis types #127

- src/components/LabelBrowser/components/LabelsSelector/LabelsList.js
- src/components/QueryItem/QueryItem.js
- src/components/QueryItem/QueryItemToolbar.js
https://github.com/metrico/qryn-view/issues/156
> Fix usequery multiple queries #156

- src/actions/getData.ts
- src/components/LabelBrowser/components/Buttons/ShowLogsButton.tsx
- src/components/LabelBrowser/components/LabelsSelector/LabelsList.js
- src/components/LabelBrowser/components/QueryBar.js
- src/components/StatusBar/components/apiselector/ApiSelector.js
- src/index.tsx
- src/plugins/settingsmenu/Menu.js
- src/store/createInitialState.ts
- src/store/reducer.ts
- src/views/DataSources/DataSource.js
- src/views/Main.js
- src/views/Main/setShowDataSourceSetting.ts
**Tasks:**
- add concatenator and datasources data after concatenator
- extract data from cookie and update datasources
-  remove datasources settings button when the cookie data is supported
- get back datasources button when there is no cookie available
**For testing purposes:**
add a 'generate cookie' button inside datasource, adding a cookie with the name of the datasource for easy identification.
cookie name : qryn-settings
> feat: Feat get data sources data from cookie #170

- src/views/DataSources/views/List.js
Fixed issue reported in #178 
Now whole "row" is clickable
> #178 fixed

- src/components/QueryItem/QueryItem.tsx
fixed: 
- Remove query at localStorage from list of recent requests when its removed from view
- fixes: #195
> Fix rm local query

- src/components/DataViews/components/ValueTags.js
- src/components/LabelBrowser/helpers/querybuilder.ts
> Fix log labels inside row

- src/App.tsx
- src/components/LabelBrowser/components/QueryBar.js
- src/components/LabelBrowser/components/ValuesList.js
- src/index.tsx
- src/providers/ProtectedRoute.js
- src/views/Main.js
- fix: extra requests of labels
- fix: missmatched url for cookies data
- add:  Protected route for datasources
> fix: extra requests to labels, protected route

- src/components/LabelBrowser/components/QuerySetting.js
- src/components/LabelBrowser/components/styled/index.ts
- src/components/QueryTypeBar/components/QueryLimit.js
- src/components/QueryTypeBar/components/QueryTypeSwitch.js
- Aligned setting options
- Got rid of white corners
For pre-fixed picture see: #200
> Fix query settings style

- src/components/StatusBar/components/copylinkbutton/CopyLinkButton.js
- src/components/StatusBar/components/daterangepicker/index.js
- src/components/StatusBar/styled/index.js
- src/helpers/UpdateStateFromQueryParams.ts
- src/plugins/queryhistory/index.js
- src/plugins/queryhistory/styled/index.js
Added dropdown to enable sharing link with relative timestamp and added initializing of the app with relative timestamp in it.
> Feature relative share link

- src/actions/setLinksHistory.ts
- src/components/LabelBrowser/components/QueryBar.js
- src/components/StatusBar/components/copylinkbutton/helpers/index.js
- src/plugins/queryhistory/index.js
- src/plugins/settingsmenu/CopyButton/CopyButton.js
- src/services/localService.ts
- src/services/localUrl.ts
Limited length of query history to 10
> Fix query history performance

- src/components/DataViews/components/QueryBuilder/styles/index.ts
- src/components/QueryItem/components/DataSourceSelectOption.tsx
Resolution: 
added custom singleValue with icon
> Fix custom select

- src/components/LabelBrowser/components/LabelsSelector/LabelsList.js
- src/components/LabelBrowser/components/LabelsSelector/ValuesSelector.js
**Resolution:** 
- 'Use Query' button has been moved to bottom of labels browser
> fix: Label Browser Button #220

- src/components/QueryItem/DataSourceSelect.tsx
- src/components/QueryItem/components/DataSourceSelectOption.tsx
added placeholder for custom select with icon for default value
> fix: #225 Placeholder for custom icon

- src/components/DataViews/components/Logs/styled.ts
- src/views/Main.tsx
> fix: #230 and #228

- src/components/DataViews/components/ValueTags.tsx
- src/components/DataViews/components/ViewHeader.tsx
- src/components/DataViews/views/LogsView.tsx
- src/components/DataViews/views/MatrixView.tsx
- src/components/DataViews/views/VectorView.tsx
- src/components/DataViews/views/styled.ts
- src/components/LabelBrowser/components/QueryBar.tsx
- src/components/QueryItem/DataSourceSelect.tsx
- src/components/QueryItem/QueriesContainer.tsx
- src/components/QueryItem/QueryItemToolbar.tsx
- src/components/QueryItem/components/DataSourceSelectOption.tsx
- src/store/createInitialState.ts
- src/views/Main.tsx
- src/views/MainTabs.tsx
> 231 change icon type for minizing response view

- src/components/LabelBrowser/components/LabelsSelector/index.tsx
- src/components/QueryItem/DataSourceSelect.tsx
- src/components/QueryItem/QueriesContainer.tsx
- src/helpers/stateFromQueryParams.ts
- src/views/Main.tsx
- src/views/Main/DesktopView.tsx
- src/views/Main/MobileView.tsx
- src/views/Main/helpers.ts
- src/views/Main/hooks.tsx
- src/views/Main/styled.tsx
- Added new initial steps for setting datasources
- If there are no cookies or url param set, will check datasources
- If datasources API is not valid, will check local url
- If local URL API is not working, will redirect to Data Source settings
> fix: Fix initial API URL by location #235

- src/views/Main/helpers.ts
> Fix initial api url

- src/actions/helpers/setColumnsValue.tsx
- src/components/DataViews/helpers.ts
- src/components/DataViews/views/LogsView.tsx
- src/components/DataViews/views/MatrixView.tsx
- src/components/DataViews/views/VectorView.tsx
- added entry at localstorage 
- Now tab state in each query will persist.
> fix: Save tab state at window resize #245

- src/views/DataSources/ui/Select.tsx
> fix: select chars limit

- .gitignore
- src/actions/loadLabelValues.ts
- src/components/DataViews/components/Metrics/helpers.ts
- src/components/DataViews/components/Metrics/useMetricsList.ts
- src/components/DataViews/components/QueryBuilder/helpers/index.tsx
- src/components/LabelBrowser/components/LabelsSelector/useLabelValues.ts
- src/components/LabelBrowser/components/LabelsSelector/useLabels.ts
- src/components/QueryBuilder/Operations/helpers/index.tsx
- src/components/TraceSearch/helpers.ts
- src/hooks/useLabels.ts
- src/views/Main/helpers.ts
- Hotfix adding extra headers for every request.
> hotfix: Headers for every request #293

- src/components/DataViews/components/Traces/Jaeger-ui/src/constants/default-config.tsx
- src/components/DataViews/components/Traces/Jaeger-ui/src/url/ReferenceLink.tsx
- src/components/LabelBrowser/components/QueryBar.tsx
- src/components/LabelBrowser/components/QuerySetting.tsx
- src/components/LabelBrowser/helpers/querybuilder.ts
- src/components/Panel/Panel.tsx
- src/components/QueryTypeBar/index.tsx
- src/components/StatusBar/components/copylinkbutton/CopyLinkButton.tsx
- src/components/StatusBar/components/copylinkbutton/index.ts
- src/helpers/UpdateStateFromQueryParams.ts
- src/helpers/decodeQuery.ts
- src/helpers/stateFromQueryParams.ts
- src/helpers/useQueryParams.ts
- src/plugins/queryhistory/index.tsx
- src/services/localUrl.ts
- src/views/DataSources/DataSources.tsx
- src/views/Main.tsx
> hotfix: strings escaping

- src/components/LabelBrowser/components/LabelsSelector/ValuesList.tsx
- src/components/LabelBrowser/components/QueryBar/QueryBar.tsx
- src/hooks/useLabels.ts
- fix extra traces search button
- fix issue selecting and deselecting label with values selection
> 337 fix some inconsistencies

- package-lock.json
- package.json
fixes: 
https://github.com/metrico/qryn-view/security/dependabot/29
https://github.com/metrico/qryn-view/security/dependabot/30
> fix: Security issues

- .github/workflows/ci-release.yml
- packages/main/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> 341 upgrade to react 18 with vite builder

- packages/main/plugins/Cardinality/Cardinality.tsx
- packages/main/plugins/Cardinality/CardinalityInput.tsx
- packages/main/plugins/Cardinality/ConfigContainerStyles.tsx
- packages/main/plugins/Cardinality/Configurator.tsx
- packages/main/plugins/Cardinality/HistorySelect.tsx
- packages/main/plugins/Cardinality/api/useCardinalityData.tsx
- packages/main/plugins/Cardinality/history/CardinalityHistoryManager.test.tsx
- packages/main/plugins/Cardinality/history/CardinalityHistoryManager.tsx
- packages/main/plugins/Cardinality/history/useCardinalityHistory.tsx
- packages/main/plugins/Cardinality/store/CardinalityStore.tsx
- packages/main/plugins/Cardinality/useConfigurator.tsx
This fixes: 
- Cardinality custom queries
- Cardinality history buttons for inputs
> feat/gp-t-460 and gp-t-458

- src/plugins/settingsmenu/MainMenu.tsx
This fixes the right menu to get it back to a simpler version.
> fix: back to simple menu

- src/views/Main/helpers.ts
Fixes the self API provisioning (from root)
> fix: datasource Self-Provisioning #363

- .github/workflows/npm_build_test.yml
> fix: workflow for gh-action-bump

- packages/main/plugins/QueryPreview.tsx
- packages/main/sections/Browser/helpers.tsx
- packages/main/src/components/DataViews/components/QueryBuilder/LogsFormBuilder.tsx
- packages/main/src/components/DataViews/components/QueryBuilder/MetricsFormBuilder.tsx
- Changes the query preview with a regular editor, working together with the query builder
> fix: query builder with editable input

- packages/main/views/Main/helpers.ts
This activates by default Cardinality feature when there is a Go backend
> fix: Cardinality active by default at GO backend

- packages/main/package.json
- packages/main/plugins/Cardinality/SeriesRow.tsx
- packages/main/plugins/Cardinality/SeriesRowHeaders.tsx
- packages/main/plugins/Cardinality/SeriesRowStyles.tsx
- packages/main/plugins/Cardinality/api/useCardinalityData.tsx
- packages/main/plugins/Cardinality/helpers.tsx
- packages/main/plugins/Cardinality/types.tsx
- packages/main/views/Main/helpers.ts
this adds a cardinality quota/ warning cell to each cardinality row
> feat: cardinality quota

- packages/main/plugins/Cardinality/Configurator.tsx
- packages/main/plugins/Cardinality/SeriesRow.tsx
- packages/main/plugins/Cardinality/Totals.tsx
- packages/main/plugins/Cardinality/api/useCardinalityData.tsx
- packages/main/plugins/Cardinality/helpers.tsx
- packages/main/plugins/Cardinality/index.tsx
- packages/main/plugins/Cardinality/store/CardinalityStore.tsx
- packages/main/plugins/PluginManagerFactory.tsx
- packages/main/views/Main/helpers.ts
- Fixes the cardinality plugin name
- Adds a plugins cleanup for when it doesn't match with locally stored plugins 
- Sets the quota percentage over cardinality at each row
- Sets the quota number at cardinality totals section
> Fix: quota value at rows

- packages/main/package.json
- packages/main/plugins/Cardinality/Totals.tsx
- packages/main/sections/Queries/QueryItem.tsx
- packages/main/sections/Queries/helpers.tsx
- Fixes the tabs state in between queries tabs
- Fixes the cero value for quota as 'unlimited'
> Fix: tab at window resize

- packages/main/services/localUrl.ts
- Fix for security issue https://github.com/metrico/qryn-view/security/code-scanning/15
> fix: initialize url params object

- BUILD.md
- README.md
This updates qryn-view documentation with new builder. 
- We switched from CRA with npm to Turbo with VITE.
- Changed to a hash router
- Added the routes
> fix: update README.md

- .github/workflows/ci-dev.yml
- .github/workflows/ci-release.yml
this updates workflows to last version.
> fix: update workflows

- packages/main/src/components/DataViews/components/QueryBuilder/FormBuilders.tsx
removes extra log uneeded at metrics
> fix: rm logs in metrics

- packages/main/src/components/DataViews/components/Table/VectorTable/styles/index.ts
- pnpm-lock.yaml
This should fix: 
- https://github.com/metrico/qryn-view/security/dependabot/44
- https://github.com/metrico/qryn-view/security/dependabot/43
- Horizontal scrollbar height
> fix: packages security updates and horizontal scrollbar

- packages/main/package.json
- packages/main/views/DataSources/components/DataSourcesFiller.tsx
- packages/main/views/DataSources/styles.ts
- packages/main/views/DataSources/styles/Container.tsx
- packages/main/views/DataSources/ui/Button.tsx
- packages/main/views/DataSources/views/Settings.tsx
- pnpm-lock.yaml
-Fix datasources URL inputs, it was broken when the user tryed to add the double slash mannually at url input.
> fix: datasources url fields

- .github/dependabot.yml
- .github/workflows/ci-release.yml
fixes the release workflow by adding wordings according to release type.
> fix: PR release versioning

- .gitignore
- packages/main/.gitignore
- packages/main/plugins/Cardinality/CardinalityDialog.tsx
- packages/main/plugins/Cardinality/Configurator.tsx
- packages/main/plugins/Cardinality/DayPicker.tsx
- packages/main/plugins/Cardinality/helpers.tsx
- packages/main/plugins/Cardinality/store/CardinalityStore.tsx
- packages/main/plugins/Cardinality/useConfigurator.tsx
- packages/main/tsconfig.json
Should fix Cardinality deletion issues at 
Refs: 
- #454 
- #453 
- [fix: Cardinality data persistance on page reload](https://github.com/metrico/qryn-view/pull/458/commits/3d396d14fa4752ba755985e413c1edf4f93ea202)
> fix: Cardinality Deletion Issues

- packages/main/plugins/Cardinality/CardinalityDialog.tsx
- packages/main/plugins/Cardinality/Configurator.tsx
- packages/main/plugins/Cardinality/consts.ts
- packages/main/plugins/Cardinality/helpers.tsx
- packages/main/plugins/Cardinality/store/CardinalityStore.tsx
- packages/main/plugins/Cardinality/useConfigurator.tsx
- packages/main/views/DataSources/ui/Select.tsx
- fix cardinality dialog for when clicking on delete button at the cardinality search section
- fixes sets of bugs from #468
> fix: cardinality dialog

- package.json
- packages/main/package.json
- packages/main/plugins/Cardinality/CardinalityDialog.tsx
- packages/main/plugins/Cardinality/helpers.tsx
- Fixes the dialog queries adding a dialog flag for the query parsing
> Fix: cardinality dialog flag for storing in local

- .github/workflows/ci-release.yml
- fix version wording for the 'Fix' keyword
> fix: version wording

- packages/main/plugins/Cardinality/CardinalityDialog.tsx
- fix: dialog query text format
- adds space after comma to improve line breaking
- adds a darker background to highlight the query text
> fix: dialog query format

- .github/workflows/ci-dev.yml
- .github/workflows/ci-release.yml
- packages/main/plugins/Cardinality/DayPicker.tsx
- packages/main/plugins/Cardinality/api/CardinalityRequest.tsx
At cardinality view, fixes the deletion timerange requested according to timezone and the response text at 500 error response.
Refs: 
- #489 
- #490
> fix: cardinality deletion response

- packages/main/qrynui/Table/models/tableModels.tsx
- packages/main/src/components/DataViews/components/Charts/QrynChart.tsx
- packages/main/src/components/DataViews/components/Charts/consts.ts
- packages/main/src/components/DataViews/components/Charts/consts/index.ts
- packages/main/src/components/DataViews/components/Charts/helpers/index.tsx
- packages/main/src/components/DataViews/components/Charts/index.tsx
- packages/main/src/components/DataViews/views/LogsView.tsx
- packages/main/src/components/DataViews/views/MatrixView.tsx
- packages/main/src/components/DataViews/views/VectorView.tsx
- fixes chart time line to the range selected at time range selector (previously the timeline only represented the timerange inside data)
> fix: chart timeline with current date range

- .github/workflows/codeql-analysis.yml
> fix: add codeql-analysis

- .gitignore
- packages/main/package.json
- packages/main/src/components/DataViews/components/Traces/Jaeger-ui/src/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx
- packages/main/src/components/DataViews/components/Traces/Jaeger-ui/src/utils/jsonMarkup.ts
- packages/main/src/components/DataViews/components/Traces/Jaeger-ui/typings/custom.d.ts
- packages/main/vite.config.ts
- pnpm-lock.yaml
Should fix security issues from: 
https://github.com/metrico/qryn-view/security/code-scanning
> fix: Incomplete HTML attribute sanitization

- packages/main/src/components/DataViews/index.tsx
- packages/main/src/components/DataViews/styled.ts
fixes: dataview scrollbar visibility 
Refs: #620
> fix: dataview scrollbar

- packages/main/src/components/LabelBrowser/components/QueryBar/QueryBar.tsx
- packages/main/src/components/StatusBar/components/daterangepicker/components/Nav.tsx
- packages/main/src/components/StatusBar/components/daterangepicker/consts.ts
- packages/main/src/components/StatusBar/components/daterangepicker/hooks/useOutsideRef.tsx
- packages/main/src/components/StatusBar/components/daterangepicker/index.tsx
- packages/main/src/components/StatusBar/components/daterangepicker/store.ts
- packages/main/src/components/StatusBar/components/daterangepicker/utils.ts
- Close time picker on clicking outside
- Timepicker button label / date range
- Daily date range
- Requests query from current search at time range change
Ref: #690
> Fix: date time range 690
